#!/usr/bin/env python3
"""
Coverage Report Viewer

Reads and displays coverage reports generated by pytest-cov.
"""

from typing import Dict, List, Optional, Any
import json
import re
from pathlib import Path


class CoverageReportError(Exception):
    """Exception raised when coverage report parsing fails."""
    pass


class CoverageReportViewer:
    """
    View and summarize pytest coverage reports.
    
    Usage:
        viewer = CoverageReportViewer()
        summary = viewer.load_report("coverage.json")
    """
    
    def __init__(self):
        """Initialize the coverage report viewer."""
        self.report_path: Optional[Path] = None
        self.data: Dict[str, Any] = {}
    
    def load_report(self, path: str) -> Dict[str, Any]:
        """Load a coverage report from JSON or HTML file."""
        self.report_path = Path(path)
        if not self.report_path.exists():
            raise CoverageReportError(f"Report not found: {path}")
        
        try:
            with open(self.report_path, "r", encoding="utf-8") as f:
                if self.report_path.suffix.lower() == ".json":
                    self.data = json.load(f)
                elif self.report_path.suffix.lower() == ".html":
                    self.data = self._parse_html(f.read())
                else:
                    raise CoverageReportError(f"Unsupported format: {self.report_path.suffix}")
        except json.JSONDecodeError as e:
            raise CoverageReportError(f"Invalid JSON report: {e}")
        except OSError as e:
            raise CoverageReportError(f"Could not read report: {e}")
        
        return self.data
    
    def _parse_html(self, html: str) -> Dict[str, Any]:
        """Extract basic metrics from HTML coverage report."""
        total_match = re.search(r"TOTAL\s+\d+\s+\d+\s+(\d+)%", html)
        files_match = re.findall(r"<td class=\"name\"><a href=\".*?\">(.*?)</a>", html)
        return {
            "coverage_percent": float(total_match.group(1)) if total_match else 0.0,
            "files": files_match,
            "source": "html"
        }
    
    def summary(self) -> Dict[str, Any]:
        """Return a concise summary of the coverage report."""
        if not self.data:
            raise CoverageReportError("No report loaded. Call load_report() first.")
        
        return {
            "coverage_percent": self.data.get("coverage_percent", 0.0),
            "files_analyzed": len(self.data.get("files", [])),
            "source": self.data.get("source", "unknown")
        }


def main():
    """CLI entry point."""
    import argparse
    parser = argparse.ArgumentParser(description="View coverage reports")
    parser.add_argument("report", help="Path to coverage report (JSON or HTML)")
    args = parser.parse_args()
    
    viewer = CoverageReportViewer()
    try:
        viewer.load_report(args.report)
        print(json.dumps(viewer.summary(), indent=2))
    except CoverageReportError as e:
        print(json.dumps({"error": str(e)}))
        exit(1)


if __name__ == "__main__":
    main()